//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_BANNER
    {
        public int IDBANNER { get; set; }
        public int IDEMPRESA { get; set; }
        public string URLBANNER { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATAINICIO { get; set; }
        public Nullable<System.DateTime> DATAFIM { get; set; }
        public string LINK { get; set; }
    }
}
