//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTAO
    {
        public int IDCARTAO { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public string IDBANDEIRA { get; set; }
        public string HASH { get; set; }
        public string NUMERO { get; set; }
        public string NOMETITULAR { get; set; }
        public string CPFTITULAR { get; set; }
        public string TELEFONETITULAR { get; set; }
        public string DATAVENC { get; set; }
        public string COD_SEGURANCA { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public string NOMECARTAO { get; set; }
    }
}
