//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_AFILIADO_PRODUTO
    {
        public int IDCLIENTE { get; set; }
        public int IDAFILIADO { get; set; }
        public int IDPRODUTO { get; set; }
        public Nullable<double> COMISSAO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public string LINK_COMPRA { get; set; }
        public string TOKEN { get; set; }
        public string LINK_VENDA_INTERNO { get; set; }
        public string LINK_VENDA_EXTERNO { get; set; }
        public Nullable<int> DIAS_PAGAMENTO { get; set; }
    }
}
