//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_CONTEUDO
    {
        public int IDCONTEUDO { get; set; }
        public int IDCLIENTE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public Nullable<System.DateTime> DATAINICIO { get; set; }
        public Nullable<System.DateTime> DATATERMINO { get; set; }
        public Nullable<int> NUMERO_PEDIDO { get; set; }
        public Nullable<int> IDMODULO { get; set; }
        public Nullable<int> IDPRODUTO { get; set; }
        public string STATUS_PLAYER { get; set; }
    }
}
