//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [JsonIgnore]
        public int IDCLIENTE { get; set; }
        public string NOME { get; set; }
        public string EMAIL { get; set; }
        public string CPF_CNPJ { get; set; }
        public string APELIDO { get; set; }
        public Nullable<System.DateTime> DATANASC { get; set; }
        public string TELEFONE1 { get; set; }
        public string TELEFONE2 { get; set; }
        public string SEXO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public string ICONE { get; set; }
        public string PAIS { get; set; }
        public string CODIGO_INDICACAO { get; set; }
        public string NOME_PUBLICO { get; set; }
        public string SITE { get; set; }
        public string SOBRE_NEGOCIO { get; set; }
        public string TOKEN { get; set; }
        public string MODO_PLAYER { get; set; }
        public Nullable<double> COMISSAO { get; set; }
        public Nullable<int> DIAS_PAGAMENTO { get; set; }
        public string FACEBOOK { get; set; }
        public string INSTAGRAM { get; set; }
        public string YOUTUBE { get; set; }
        public string PINTEREST { get; set; }
        public string WEBSITE { get; set; }
        public string INDICADO_POR { get; set; }
    }
}
