//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_PERFIL
    {
        public int IDCLIENTE { get; set; }
        public int IDPERFIL { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public Nullable<int> CLIENTEPAI { get; set; }
    }
}
