//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_BANCARIA
    {
        public int IDCONTA { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> NUMERO_BANCO { get; set; }
        public string NOMEBANCO { get; set; }
        public string AGENCIA { get; set; }
        public string CONTA { get; set; }
        public string OPERACAO { get; set; }
        public string CPFTITULAR { get; set; }
        public string NOMETITULAR { get; set; }
        public string CODIGO_MEIOPAGAMENTO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public string TIPO_CONTA { get; set; }
        public string TOKENJUNO { get; set; }
    }
}
