//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTEUDO
    {
        public int IDCONTEUDO { get; set; }
        public string TITULO { get; set; }
        public string DESCRICAO { get; set; }
        public string MINIATURA { get; set; }
        public Nullable<int> IDPROVEDOR { get; set; }
        public string LINK { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public Nullable<int> IDMODULO { get; set; }
        public Nullable<int> ORDEM { get; set; }
        public string LINK_CURTO { get; set; }
        public string HTML { get; set; }
    }
}
