//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUPOM
    {
        public int IDCUPOM { get; set; }
        public string CODIGO { get; set; }
        public string DESCRICAO { get; set; }
        public string TIPO { get; set; }
        public Nullable<double> PORCENTAGEM { get; set; }
        public Nullable<System.DateTime> DATA_INICIO { get; set; }
        public Nullable<System.DateTime> DATA_FIM { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public Nullable<int> QTDE { get; set; }
        public Nullable<int> QTDE_CLIENTE { get; set; }
    }
}
