//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_DISPARO
    {
        public int IDEMAIL { get; set; }
        public string EMAIL_PARA { get; set; }
        public string EMAIL_DE { get; set; }
        public string EMAIL_ASSUNTO { get; set; }
        public string EMAIL_CORPO { get; set; }
        public Nullable<System.DateTime> EMAIL_DATA_GRAVACAO { get; set; }
        public Nullable<System.DateTime> EMAIL_DATA_ENVIO { get; set; }
        public Nullable<int> EMAIL_TENTATIVA_ENVIO { get; set; }
        public Nullable<int> EMAIL_ENVIADO { get; set; }
    }
}
