//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trampowEntidades : DbContext
    {
        public trampowEntidades()
            : base("name=trampowEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CLIENTE>().ToTable("CLIENTE");
        }
    
        public virtual DbSet<APP_BANNER> APP_BANNER { get; set; }
        public virtual DbSet<CARTAO> CARTAO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CLIENTE_AFILIADO_PRODUTO> CLIENTE_AFILIADO_PRODUTO { get; set; }
        public virtual DbSet<CLIENTE_CONTEUDO> CLIENTE_CONTEUDO { get; set; }
        public virtual DbSet<CLIENTE_ENDERECO> CLIENTE_ENDERECO { get; set; }
        public virtual DbSet<CLIENTE_PERFIL> CLIENTE_PERFIL { get; set; }
        public virtual DbSet<CONFIRMA_CLIENTE> CONFIRMA_CLIENTE { get; set; }
        public virtual DbSet<CUPOM_CLIENTE> CUPOM_CLIENTE { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PEDIDO_ITEM> PEDIDO_ITEM { get; set; }
        public virtual DbSet<PRODUTO> PRODUTO { get; set; }
        public virtual DbSet<PRODUTO_FERRAMENTA> PRODUTO_FERRAMENTA { get; set; }
        public virtual DbSet<RECUPERA_SENHA> RECUPERA_SENHA { get; set; }
        public virtual DbSet<SCORE_PRODUTO> SCORE_PRODUTO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<BANDEIRA> BANDEIRA { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<CONTA_BANCARIA> CONTA_BANCARIA { get; set; }
        public virtual DbSet<CONTEUDO> CONTEUDO { get; set; }
        public virtual DbSet<CUPOM> CUPOM { get; set; }
        public virtual DbSet<EMAIL_DISPARO> EMAIL_DISPARO { get; set; }
        public virtual DbSet<EXTRATO> EXTRATO { get; set; }
        public virtual DbSet<FERRAMENTA> FERRAMENTA { get; set; }
        public virtual DbSet<FORMA_PAGAMENTO> FORMA_PAGAMENTO { get; set; }
        public virtual DbSet<FORMATO> FORMATO { get; set; }
        public virtual DbSet<IDIOMA> IDIOMA { get; set; }
        public virtual DbSet<NOTIFICACAO> NOTIFICACAO { get; set; }
        public virtual DbSet<PARCELA> PARCELA { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PLATAFORMA> PLATAFORMA { get; set; }
        public virtual DbSet<PRODUTO_DIVULGACAO> PRODUTO_DIVULGACAO { get; set; }
        public virtual DbSet<PRODUTO_MODULO> PRODUTO_MODULO { get; set; }
        public virtual DbSet<PROVEDOR> PROVEDOR { get; set; }
        public virtual DbSet<SAQUE> SAQUE { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
    }
}
