//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICACAO
    {
        public int IDMENSAGEM { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public string TIPO { get; set; }
        public string MENSAGEM { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public Nullable<System.DateTime> DATAVISUALIZA { get; set; }
        public string LINK { get; set; }
    }
}
