//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public List<PEDIDO_ITEM> ITEMS { get; set; }
        [JsonIgnore]
        public int NUMERO_PEDIDO { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<double> VALOR { get; set; }
        public Nullable<double> FRETE { get; set; }
        public Nullable<double> DESCONTO { get; set; }
        public Nullable<int> IDCUPOM { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public string OBSERVACAO { get; set; }
        public Nullable<int> IDFORMAPAGAMENTO { get; set; }
        public Nullable<int> IDCARTAO { get; set; }
        public Nullable<int> QTDEPARCELA { get; set; }
        public Nullable<int> PONTOS { get; set; }
        public Nullable<int> IDAFILIADO { get; set; }
        public Nullable<int> IDPRODUTOR { get; set; }
        public string TIPOVENDA { get; set; }
        public string TOKEN { get; set; }
    }
}
