//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATAFORMA
    {
        public int IDPLATAFORMA { get; set; }
        public string NOMEPLATAFORMA { get; set; }
        public Nullable<double> COMISSAO { get; set; }
        public Nullable<int> DIAS_PAGAMENTO { get; set; }
        public string SITE_OFICIAL { get; set; }
        public string MEIO_PAGAMENTO { get; set; }
        public Nullable<double> PERC_MEIO_PAGAMENTO { get; set; }
    }
}
