//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        public int IDPRODUTO { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public string DESCRICAO_BREVE { get; set; }
        public string DESCRICAO_COMPLETA { get; set; }
        public Nullable<double> VALOR { get; set; }
        public Nullable<double> VALOR_PROMOCIONAL { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public string METATAGS { get; set; }
        public string METADESCRICAO { get; set; }
        public Nullable<int> GARANTIA { get; set; }
        public string TITULO { get; set; }
        public Nullable<int> IDCATEGORIA { get; set; }
        public string MINIATURA { get; set; }
        public string TOKEN { get; set; }
        public Nullable<int> VIEWS { get; set; }
        public string TIPO { get; set; }
        public string LINKPRODUTO { get; set; }
        public string DESTAQUE { get; set; }
    }
}
