//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_MODULO
    {
        public int IDMODULO { get; set; }
        public Nullable<int> IDPRODUTO { get; set; }
        public string NOMEMODULO { get; set; }
        public Nullable<bool> GRATUITO { get; set; }
        public string MINIATURA { get; set; }
        public Nullable<int> QTDE_AULAS { get; set; }
        public Nullable<int> CARGA_HORARIA { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public string DESCRICAO { get; set; }
    }
}
