//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEDOR
    {
        public int IDPROVEDOR { get; set; }
        public string NOMEPROVEDOR { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public string TOKEN { get; set; }
        public string URLAPI { get; set; }
        public string CONSUMEKEY { get; set; }
        public string CREDENCIAL { get; set; }
    }
}
