//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS
    {
        public int IDSTATUS { get; set; }
        public string DESCRICAO_STATUS { get; set; }
        public string ABREV_STATUS { get; set; }
        public string STATUS1 { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
    }
}
