//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestTedie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trampowEntities : DbContext
    {
        public trampowEntities()
            : base("name=trampowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE_AFILIADO_PRODUTO> CLIENTE_AFILIADO_PRODUTO { get; set; }
        public virtual DbSet<CLIENTE_CONTEUDO> CLIENTE_CONTEUDO { get; set; }
        public virtual DbSet<CLIENTE_PERFIL> CLIENTE_PERFIL { get; set; }
        public virtual DbSet<CONFIRMA_CLIENTE> CONFIRMA_CLIENTE { get; set; }
        public virtual DbSet<CUPOM_CLIENTE> CUPOM_CLIENTE { get; set; }
        public virtual DbSet<PEDIDO> PEDIDOes { get; set; }
        public virtual DbSet<PEDIDO_ITEM> PEDIDO_ITEM { get; set; }
        public virtual DbSet<PRODUTO_FERRAMENTA> PRODUTO_FERRAMENTA { get; set; }
        public virtual DbSet<RECUPERA_SENHA> RECUPERA_SENHA { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<BANDEIRA> BANDEIRAs { get; set; }
        public virtual DbSet<CARTAO> CARTAOs { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIAs { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<CLIENTE_ENDERECO> CLIENTE_ENDERECO { get; set; }
        public virtual DbSet<CONTA_BANCARIA> CONTA_BANCARIA { get; set; }
        public virtual DbSet<CONTEUDO> CONTEUDOes { get; set; }
        public virtual DbSet<CUPOM> CUPOMs { get; set; }
        public virtual DbSet<EMAIL_DISPARO> EMAIL_DISPARO { get; set; }
        public virtual DbSet<EXTRATO> EXTRATOes { get; set; }
        public virtual DbSet<FERRAMENTA> FERRAMENTAs { get; set; }
        public virtual DbSet<FORMA_PAGAMENTO> FORMA_PAGAMENTO { get; set; }
        public virtual DbSet<FORMATO> FORMATOes { get; set; }
        public virtual DbSet<IDIOMA> IDIOMAs { get; set; }
        public virtual DbSet<NOTIFICACAO> NOTIFICACAOs { get; set; }
        public virtual DbSet<PARCELA> PARCELAs { get; set; }
        public virtual DbSet<PERFIL> PERFILs { get; set; }
        public virtual DbSet<PLATAFORMA> PLATAFORMAs { get; set; }
        public virtual DbSet<PRODUTO> PRODUTOes { get; set; }
        public virtual DbSet<PRODUTO_DIVULGACAO> PRODUTO_DIVULGACAO { get; set; }
        public virtual DbSet<PRODUTO_MODULO> PRODUTO_MODULO { get; set; }
        public virtual DbSet<PROVEDOR> PROVEDORs { get; set; }
        public virtual DbSet<SAQUE> SAQUEs { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
    }
}
